name: library_33880
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  enum_flag: ^1.0.2
  flex_color_picker: ^3.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  html: ^0.15.4
  http: ^1.0.0
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
